pipeline {
    agent any

    stages {
        stage('Prepare') {
            steps {
                echo 'Installing Node.js version 22...'
                sh '''
                    sudo kill -9 $(sudo lsof -t /var/lib/dpkg/lock-frontend) || true
                    sudo rm /var/lib/dpkg/lock-frontend || true
                    sudo rm /var/lib/dpkg/lock || true
                    sudo dpkg --configure -a || true
                    curl -sL https://deb.nodesource.com/setup_22.x | sudo -E bash -
                    sudo apt-get install -y nodejs
                '''
            }
        }

        stage('Build') {
            steps {
                echo 'Building...'
                sh 'node -v'
                sh 'npm -v'
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests...'
                sh 'echo $JENKINS_URL'
            }
        }
    }
}
